# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0e32ffec41824d0cf542ac7aaa5eaa148275a4172b56510d7f55bfed1acea4208759df39d1d9ff3670b015b38ebfe70bb938bc020bb7be1aa2c1262ea1a7231

test:
  secret_key_base: c9bec916d4c1252841335babde7a754826f2ebbca43668c5d047d23e2618772ced1dc9e9d5093962fb1877aa3b5ea4b060bfca2ce413ab1602e5e88aad214e26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
